# Generated by Django 3.2.8 on 2021-10-18 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implementation_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tikets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tikets_PIP', models.CharField(max_length=200)),
                ('tikets_email', models.EmailField(max_length=254)),
                ('tikets_Phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('tikets_Location', models.CharField(max_length=200)),
                ('tikets_text', models.CharField(max_length=200)),
                ('tikets_pub_date', models.DateTimeField(auto_now_add=True)),
                ('tikets_implementation_date', models.DateTimeField(null=True)),
                ('tikets_Owner_date', models.DateTimeField(null=True)),
                ('tikets_Owner', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Відповідальний')),
                ('tikets_Topic', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tikets.topic')),
                ('tikets_implementation', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tikets.implementation')),
            ],
        ),
    ]
