# Generated by Django 3.2.8 on 2021-10-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tikets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tikets',
            name='tikets_Owner',
        ),
    ]
