# Generated by Django 3.2.8 on 2021-10-18 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tikets', '0002_remove_tikets_tikets_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tikets',
            name='tikets_Owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Відповідальний'),
        ),
    ]
