# Generated by Django 3.2.8 on 2021-10-18 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tikets', '0003_tikets_tikets_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tikets',
            name='tikets_implementation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tikets.implementation'),
        ),
    ]
