# Generated by Django 3.2.8 on 2021-11-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tikets', '0004_alter_tikets_tikets_implementation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tikets',
            name='tikets_Owner_date',
        ),
    ]
